# Bayesian Kendall's tau (van Doorn, Ly, Marsman & Wagenmakers 2018) ----------
#
# Oracle records (one line per oracle: id | type | asserting test | source and
# provenance). The asserting test is the record of the value; nothing here
# restates a number a test does not assert.
#
# K1  | frozen (two independent implementations) | "AC2: the helper matches
#       the paper's OSF code and bstats on the 36-cell grid"
#       | bayes_kendall_reference below: BF10, posterior median, and equal-tailed
#       95% interval from the paper's own R_Code_KendallBayesFactor.R
#       (https://osf.io/b9qhj/) and from AlexanderLyNL/bstats R/kendall.R at
#       commit 42d34c1; generated by data-raw/bayes_kendall_reference.R; both
#       sources evaluate the interval on a grid (steps 0.002 and 0.0005), which
#       the 3e-3 absolute tolerance on median and endpoints covers.
# K2  | frozen (published) | "AC3: the Fig. 5 brain-size example reproduces"
#       | van Doorn et al. (2018) Fig. 5, p. 307: Kendall BF10 2.170 and Pearson
#       BF10 5.158 read against the source (cairn/references/vandoorn2018.md);
#       median 0.291 and interval [0.006, 0.571] are the OSF code's values on
#       the same 20 rows (the printed interval does not reproduce from that
#       code). Data: tests/testthat/fixtures/brain_size.csv, FSIQ >= 130.
# K3  | closed-form | "AC4: at tau = 0 and scale 1 the BF is the integral of
#       eqs. (10) and (13)" | BF10 = integral over [-1, 1] of
#       exp(-(1.5 tau sqrt(n))^2 / 2) * (pi/4) cos(pi tau / 2), transcribed
#       from vandoorn2018 p. 305 and integrated with stats::integrate().
# K4  | invariant | "AC4: mirror symmetry in the observed tau"
#       | the model is even in tau: negating the observed tau keeps BF and
#       negates and swaps the median and interval endpoints.
# K5  | invariant | "AC5: pd and ROPE_Percentage are masses of the same
#       posterior" | pd and the interval must agree on excluding 0; the ROPE
#       mass recomputed by integrating the helper's own posterior density.
# K6  | live | "AC1: a Bayesian Kendall row differs from the Bayesian Pearson
#       row" | BayesFactor::correlationBF() on the raw data (what the package
#       returned under this method before, issue #224).

.bk <- function(n, tau, scale, ci = 0.95, ci_method = "eti") {
  .bayes_kendall_posterior(
    n = n,
    tau = tau,
    scale = scale,
    ci = ci,
    ci_method = ci_method
  )
}

.read_brain_size <- function() {
  d <- read.csv(
    test_path("fixtures", "brain_size.csv"),
    comment.char = "#"
  )
  d[d$FSIQ >= 130, ]
}

# Generated by data-raw/bayes_kendall_reference.R from the two shelved
# implementations (see K1); scale is the prior scale (alpha = 1/scale).
bayes_kendall_reference <- data.frame(
  n = c(
    10,
    10,
    10,
    10,
    20,
    20,
    20,
    20,
    50,
    50,
    50,
    50,
    10,
    10,
    10,
    10,
    20,
    20,
    20,
    20,
    50,
    50,
    50,
    50
  ),
  tau = c(
    -0.3,
    0,
    0.2,
    0.5,
    -0.3,
    0,
    0.2,
    0.5,
    -0.3,
    0,
    0.2,
    0.5,
    -0.3,
    0,
    0.2,
    0.5,
    -0.3,
    0,
    0.2,
    0.5,
    -0.3,
    0,
    0.2,
    0.5
  ),
  scale = c(
    1 / 3,
    1 / 3,
    1 / 3,
    1 / 3,
    1 / 3,
    1 / 3,
    1 / 3,
    1 / 3,
    1 / 3,
    1 / 3,
    1 / 3,
    1 / 3,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
  ),
  osf_bf = c(
    0.980174,
    0.621237,
    0.761199,
    2.18263,
    1.825,
    0.486306,
    0.876717,
    18.5477,
    22.8354,
    0.330211,
    2.17729,
    39649.9,
    0.750238,
    0.392894,
    0.524049,
    2.3407,
    1.43301,
    0.28554,
    0.585297,
    24.7751,
    18.5879,
    0.183587,
    1.43068,
    66788.9
  ),
  osf_median = c(
    -0.160321,
    -0.00200401,
    0.106212,
    0.262525,
    -0.214429,
    -1.11022e-16,
    0.142285,
    0.348697,
    -0.260521,
    -0.00200401,
    0.172345,
    0.42485,
    -0.226453,
    -1.11022e-16,
    0.150301,
    0.370741,
    -0.260521,
    -1.11022e-16,
    0.172345,
    0.428858,
    -0.284569,
    -1.11022e-16,
    0.188377,
    0.468938
  ),
  osf_low = c(
    -0.476954,
    -0.328657,
    -0.222445,
    -0.0621242,
    -0.46493,
    -0.258517,
    -0.116232,
    0.0961924,
    -0.432866,
    -0.176353,
    -0.00200401,
    0.254509,
    -0.607214,
    -0.390782,
    -0.240481,
    -0.0140281,
    -0.541082,
    -0.284569,
    -0.112224,
    0.148297,
    -0.466934,
    -0.184369,
    0.00601202,
    0.286573
  ),
  osf_high = c(
    0.168337,
    0.326653,
    0.426854,
    0.56513,
    0.0420842,
    0.256513,
    0.39479,
    0.587174,
    -0.0861723,
    0.174349,
    0.346693,
    0.593186,
    0.162325,
    0.388778,
    0.53507,
    0.735471,
    0.0220441,
    0.282565,
    0.45491,
    0.701403,
    -0.102204,
    0.182365,
    0.370741,
    0.649299
  ),
  bstats_bf = c(
    0.980174,
    0.621237,
    0.761199,
    2.18263,
    1.825,
    0.486306,
    0.876717,
    18.5477,
    22.8354,
    0.330211,
    2.17729,
    39649.9,
    0.750238,
    0.392894,
    0.524049,
    2.3407,
    1.43301,
    0.28554,
    0.585297,
    24.7751,
    18.5879,
    0.183587,
    1.43068,
    66788.9
  ),
  bstats_median = c(
    -0.16058,
    -1.11022e-16,
    0.107054,
    0.262631,
    -0.213107,
    -1.11022e-16,
    0.142571,
    0.348674,
    -0.25963,
    -1.11022e-16,
    0.173087,
    0.426213,
    -0.226613,
    -1.11022e-16,
    0.151076,
    0.372186,
    -0.26013,
    -1.11022e-16,
    0.173587,
    0.429215,
    -0.283142,
    -1.11022e-16,
    0.188594,
    0.469735
  ),
  bstats_low = c(
    -0.476738,
    -0.327164,
    -0.222111,
    -0.0625313,
    -0.463732,
    -0.257629,
    -0.115058,
    0.0965483,
    -0.432216,
    -0.175588,
    -0.002001,
    0.255128,
    -0.606803,
    -0.389695,
    -0.23962,
    -0.014007,
    -0.54077,
    -0.284142,
    -0.110555,
    0.148574,
    -0.465233,
    -0.183092,
    0.006003,
    0.288144
  ),
  bstats_high = c(
    0.168084,
    0.326663,
    0.427714,
    0.566283,
    0.0435218,
    0.257129,
    0.396198,
    0.588294,
    -0.0850425,
    0.175088,
    0.347174,
    0.593797,
    0.163582,
    0.389195,
    0.535768,
    0.735868,
    0.0235118,
    0.283642,
    0.455728,
    0.702851,
    -0.101051,
    0.182591,
    0.371186,
    0.649825
  )
)

# The 36 cells of the AC2 grid: each numeric-scale row, plus the "medium" cells
# (which must equal the 1/3 cells exactly).
.grid_scales <- function(scale) {
  if (isTRUE(all.equal(scale, 1 / 3))) list(1 / 3, "medium") else list(1)
}

test_that("AC1: cor_test and correlation report a Bayesian Kendall row", {
  out <- cor_test(mtcars, "mpg", "cyl", method = "kendall", bayesian = TRUE)
  expect_s3_class(out, "easycor_test")
  expect_identical(nrow(out), 1L)
  for (col in c(
    "tau",
    "CI",
    "CI_low",
    "CI_high",
    "pd",
    "ROPE_Percentage",
    "Prior_Distribution",
    "Prior_Location",
    "Prior_Scale",
    "BF",
    "Method",
    "n_Obs"
  )) {
    expect_true(col %in% names(out), label = paste("column", col))
  }
  expect_identical(out$Method, "Bayesian Kendall")
  expect_identical(attr(out, "coefficient_name"), "tau")

  # The tied pair reports the helper's BF at n = 32 and the observed tau-b.
  tau_b <- stats::cor(mtcars$mpg, mtcars$cyl, method = "kendall")
  ref <- .bk(n = 32, tau = tau_b, scale = "medium", ci_method = "hdi")
  expect_identical(out$n_Obs, 32L)
  expect_equal(out$BF, ref$BF)
  expect_equal(out$tau, ref$tau)

  skip_if_not_installed("BayesFactor")
  ken <- correlation(mtcars[, 1:3], method = "kendall", bayesian = TRUE)
  pea <- correlation(mtcars[, 1:3], method = "pearson", bayesian = TRUE)
  expect_identical(nrow(ken), 3L)
  expect_true(all(ken$Method == "Bayesian Kendall correlation"))
  expect_true("tau" %in% names(ken))
  # The #224 reprex: every row differs from the Bayesian Pearson estimate.
  expect_true(all(abs(ken$tau - pea$rho) > 1e-3))
})

test_that("AC1: bayesian_test selects the reported tests as the Pearson row does", {
  out <- cor_test(
    mtcars,
    "mpg",
    "cyl",
    method = "kendall",
    bayesian = TRUE,
    bayesian_test = "pd"
  )
  expect_true("pd" %in% names(out))
  expect_false("ROPE_Percentage" %in% names(out))
  expect_true(is.na(out$BF))
})

test_that("AC2: the helper matches the paper's OSF code and bstats on the 36-cell grid", {
  ref <- bayes_kendall_reference
  for (i in seq_len(nrow(ref))) {
    for (scale in .grid_scales(ref$scale[i])) {
      lab <- sprintf(
        "n = %d, tau = %s, scale = %s",
        ref$n[i],
        ref$tau[i],
        format(scale)
      )
      res <- .bk(n = ref$n[i], tau = ref$tau[i], scale = scale)
      # BF: relative tolerance 1e-3 against both sources
      expect_lt(
        abs(res$BF / ref$osf_bf[i] - 1),
        1e-3,
        label = paste("OSF BF", lab)
      )
      expect_lt(
        abs(res$BF / ref$bstats_bf[i] - 1),
        1e-3,
        label = paste("bstats BF", lab)
      )
      # median and equal-tailed endpoints: absolute tolerance 3e-3
      expect_lt(
        abs(res$tau - ref$osf_median[i]),
        3e-3,
        label = paste("OSF median", lab)
      )
      expect_lt(
        abs(res$CI_low - ref$osf_low[i]),
        3e-3,
        label = paste("OSF low", lab)
      )
      expect_lt(
        abs(res$CI_high - ref$osf_high[i]),
        3e-3,
        label = paste("OSF high", lab)
      )
      expect_lt(
        abs(res$tau - ref$bstats_median[i]),
        3e-3,
        label = paste("bstats median", lab)
      )
      expect_lt(
        abs(res$CI_low - ref$bstats_low[i]),
        3e-3,
        label = paste("bstats low", lab)
      )
      expect_lt(
        abs(res$CI_high - ref$bstats_high[i]),
        3e-3,
        label = paste("bstats high", lab)
      )
    }
    if (isTRUE(all.equal(ref$scale[i], 1 / 3))) {
      a <- .bk(n = ref$n[i], tau = ref$tau[i], scale = 1 / 3)
      b <- .bk(n = ref$n[i], tau = ref$tau[i], scale = "medium")
      keys <- c("tau", "CI_low", "CI_high", "pd", "ROPE_Percentage", "BF")
      expect_identical(a[keys], b[keys])
    }
  }
})

test_that("AC3: the Fig. 5 brain-size example reproduces", {
  d <- .read_brain_size()
  expect_identical(nrow(d), 20L)
  out <- cor_test(
    d,
    "FSIQ",
    "MRI_Count",
    method = "kendall",
    bayesian = TRUE,
    bayesian_prior = 1,
    bayesian_ci_method = "eti"
  )
  expect_lt(abs(out$BF - 2.170), 0.005)
  expect_lt(abs(out$tau - 0.291), 0.005)
  expect_lt(abs(out$CI_low - 0.006), 0.005)
  expect_lt(abs(out$CI_high - 0.571), 0.005)

  skip_if_not_installed("BayesFactor")
  pea <- cor_test(d, "FSIQ", "MRI_Count", bayesian = TRUE, bayesian_prior = 1)
  expect_lt(abs(pea$BF - 5.158), 0.005)
})

test_that("AC4: at tau = 0 and scale 1 the BF is the integral of eqs. (10) and (13)", {
  for (n in c(5, 20, 100)) {
    # eq. (10): p(tau) = (pi/4) cos(pi tau / 2); eq. (13) with T* = 0:
    # BF10 = integral of exp(-(1.5 tau sqrt(n))^2 / 2) * p(tau) over [-1, 1].
    integrand <- function(tau) {
      exp(-(1.5 * tau * sqrt(n))^2 / 2) * (pi / 4) * cos(pi * tau / 2)
    }
    bf_closed <- stats::integrate(integrand, -1, 1, rel.tol = 1e-10)$value
    res <- .bk(n = n, tau = 0, scale = 1)
    expect_lt(abs(res$BF / bf_closed - 1), 1e-6, label = paste("n =", n))
    expect_lt(abs(res$tau), 1e-6, label = paste("median, n =", n))
    expect_lt(
      abs(res$CI_low + res$CI_high),
      1e-6,
      label = paste("endpoints, n =", n)
    )
  }
})

test_that("AC4: mirror symmetry in the observed tau", {
  ref <- bayes_kendall_reference
  for (i in seq_len(nrow(ref))) {
    for (scale in .grid_scales(ref$scale[i])) {
      lab <- sprintf(
        "n = %d, tau = %s, scale = %s",
        ref$n[i],
        ref$tau[i],
        format(scale)
      )
      plus <- .bk(n = ref$n[i], tau = ref$tau[i], scale = scale)
      minus <- .bk(n = ref$n[i], tau = -ref$tau[i], scale = scale)
      expect_lt(abs(minus$BF / plus$BF - 1), 1e-9, label = paste("BF", lab))
      expect_lt(abs(minus$tau + plus$tau), 1e-6, label = paste("median", lab))
      expect_lt(
        abs(minus$CI_low + plus$CI_high),
        1e-6,
        label = paste("low", lab)
      )
      expect_lt(
        abs(minus$CI_high + plus$CI_low),
        1e-6,
        label = paste("high", lab)
      )
    }
  }
})

test_that("AC5: pd and ROPE_Percentage are masses of the same posterior", {
  ref <- bayes_kendall_reference
  for (i in seq_len(nrow(ref))) {
    for (scale in .grid_scales(ref$scale[i])) {
      lab <- sprintf(
        "n = %d, tau = %s, scale = %s",
        ref$n[i],
        ref$tau[i],
        format(scale)
      )
      res <- .bk(n = ref$n[i], tau = ref$tau[i], scale = scale)
      if (ref$tau[i] == 0) {
        expect_lt(abs(res$pd - 0.5), 1e-6, label = paste("pd at 0", lab))
      }
      excludes_zero <- res$CI_low > 0 || res$CI_high < 0
      expect_identical(
        res$pd > 0.975,
        excludes_zero,
        label = paste("pd vs interval", lab)
      )
      expect_gte(res$ROPE_Percentage, 0)
      expect_lte(res$ROPE_Percentage, 1)
      rope_mass <- stats::integrate(
        res$posterior,
        -0.1,
        0.1,
        rel.tol = 1e-8
      )$value
      expect_lt(
        abs(res$ROPE_Percentage - rope_mass),
        1e-4,
        label = paste("ROPE", lab)
      )
    }
  }
})

test_that("AC5: the default hdi interval is the highest-density interval", {
  d <- .read_brain_size()
  hdi <- cor_test(d, "FSIQ", "MRI_Count", method = "kendall", bayesian = TRUE)
  eti <- cor_test(
    d,
    "FSIQ",
    "MRI_Count",
    method = "kendall",
    bayesian = TRUE,
    bayesian_ci_method = "eti"
  )
  expect_identical(hdi$tau, eti$tau)
  expect_lte(hdi$CI_high - hdi$CI_low, eti$CI_high - eti$CI_low)
  expect_true(hdi$CI_low < hdi$tau && hdi$tau < hdi$CI_high)
  # The HDI carries the requested mass and has equal density at its ends.
  res <- .bk(
    n = 20,
    tau = stats::cor(d$FSIQ, d$MRI_Count, method = "kendall"),
    scale = "medium",
    ci_method = "hdi"
  )
  mass <- stats::integrate(
    res$posterior,
    res$CI_low,
    res$CI_high,
    rel.tol = 1e-8
  )$value
  expect_lt(abs(mass - 0.95), 1e-4)
  expect_lt(abs(res$posterior(res$CI_low) - res$posterior(res$CI_high)), 1e-3)
})

test_that("AC7: x == y and perfectly monotone pairs", {
  same <- cor_test(mtcars, "mpg", "mpg", method = "kendall", bayesian = TRUE)
  expect_identical(same$tau, 1)
  expect_identical(same$CI_low, 1)
  expect_identical(same$CI_high, 1)
  expect_identical(same$pd, 1)
  expect_identical(same$ROPE_Percentage, 0)
  expect_identical(same$BF, Inf)

  up <- data.frame(x = 1:10, y = (1:10)^2)
  down <- data.frame(x = 1:10, y = -(1:10)^3)
  for (prior in list("medium", 1)) {
    out_up <- cor_test(
      up,
      "x",
      "y",
      method = "kendall",
      bayesian = TRUE,
      bayesian_prior = prior
    )
    out_down <- cor_test(
      down,
      "x",
      "y",
      method = "kendall",
      bayesian = TRUE,
      bayesian_prior = prior
    )
    expect_gt(out_up$tau, 0)
    expect_lt(out_down$tau, 0)
    expect_true(all(is.finite(c(
      out_up$CI_low,
      out_up$CI_high,
      out_down$CI_low,
      out_down$CI_high
    ))))
    expect_gt(out_up$BF, 1)
    expect_gt(out_down$BF, 1)
  }
})
